### ISSUE TITLE
config.status: error: cannot find input file: `Makefile.in'

### ISSUE THREAD

**Issue by ghost** [firnsy/yubipam#1]
Hey,

I keep getting this error: "config.status: error: cannot find input file: `Makefile.in'" while performing "./configure". Any ideas?

I am using the latest commit (19th April 2012), Ubuntu 11.10. Tried to get PAM headers like the instructions said by installing "libpam0g-dev". Was that sufficient? Please let me know if I should be providing more information.

Thanks,
James

**Comment by hxpax** [comment]
Got the same error on Ubuntu 1404 with autoreconf.

**Comment by OnnoKampman** [comment]
Got the same error, fixed it as follows.

It turned out I had a folder in the path to the openSMILE folder with a space in the folder name. './configure' couldn't deal with that. After removing the white space it executed.

**Comment by shivammutreja** [comment]
Anybody here while installing secp256k1. Follow this answer - https://stackoverflow.com/a/22625555/4631231

**Comment by malikabid** [comment]
.in'ig.status: error: cannot find input file: `Makefile
